nome = input('Qual é o seu nome? ')
cpf = input('Digite o seu cpf por favor ')
endereco = input('Qual é o seu endereço? ')
idade = input('Quantos anos você tem? ')
altura = input('Qual é sua altura?')
telefone = input('Qual é o deu telefone? ')
print('O ', nome, ' de cpf ', cpf, 'possui ', idade, 'anos.')
print('Mora em ', endereco, ', o telefone é ', telefone, 'e possui de altura', altura, '.')